### ISSUE TITLE
Should we use feature detection instead of UA detection?

### ISSUE THREAD

**Issue by hax** [fanmingfei/array-reverse-ios12#10]
The UA detection is complex and hard to be accurate. I think UA detection is more suitable for polyfill loader or server adaption (like polyfill.io). The polyfill itself should use feature (really bug😂) detection.

```js
function buggy() {
  var a = init(), b = init()
  a.reverse()
  if (b[0] !== 0) {
    a.reverse() // recover
    return true
  } else return false
  function init() { return [0, 1] }
}
if (buggy()) patch()
```

**Comment by fanmingfei** [comment]
I think so, but that your code is not work.
Have try this:
```js
function buggy() {
     function detect() {
       var a = [0,1];
       a.reverse();
       return a[0] === 0;
     }
     return detect() || detect();
}
```

**Comment by justjavac** [comment]
https://jsperf.com/array-reverse-ios12-detection

**Comment by hax** [comment]
@fanmingfei Yes, I should use the same initializer. Fixed now.

**Comment by fanmingfei** [comment]
Needn't refresh page. I rewrite the demos.

[Not Fixed](https://fanmingfei.github.io/array-reverse-ios12/origin.html)
[Fixed](https://fanmingfei.github.io/array-reverse-ios12/fixed.html)

**Comment by fanmingfei** [comment]
done
